// Socle client : session Supabase, appels Data API, identité métier et catalogue.
// Les autorisations réelles restent contrôlées par PostgreSQL/RLS et les RPC.
const app=document.querySelector('#app');
const SUPABASE_URL='https://cvaysurwzkphmsvqujab.supabase.co';
const SUPABASE_KEY='sb_publishable_EvO6xjIFQH74h-p7hXLQ-Q_oEmvcWCo';
const REAPPRO_TYPE='1f51c270-d2f1-4ea0-a22d-5a70579b6e7b';
let cart=[],products=[],catalogReady=false,currentUser=null,accessToken=sessionStorage.getItem('bm_access_token')||'',pendingRequestOperationId=null;

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function brandMark(compact=false){return `<div class="brand ${compact?'compact':''}" aria-label="Parfumerie SAM"><svg viewBox="0 0 48 48" role="img" aria-hidden="true"><path d="M18 5h12v6H18z"/><path d="M15 13h18l4 8v18c0 2.2-1.8 4-4 4H15c-2.2 0-4-1.8-4-4V21l4-8z"/><path class="brand-s" d="M29.5 22c-1.5-1.4-3.2-2-5.5-2-2.8 0-4.8 1.3-4.8 3.3 0 5 10.2 2.1 10.2 8 0 2.6-2.3 4.5-5.7 4.5-2.4 0-4.6-.8-6.2-2.4"/></svg><span><b>SAM</b>${compact?'':'<small>PARFUMERIE</small>'}</span></div>`}

async function request(path,{method='GET',body,auth=false,headers:extra={}}={}){const headers={apikey:SUPABASE_KEY,'Content-Type':'application/json',...extra};if(auth&&accessToken)headers.Authorization=`Bearer ${accessToken}`;const response=await fetch(`${SUPABASE_URL}${path}`,{method,headers,body:body?JSON.stringify(body):undefined});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!response.ok)throw new Error(data?.message||data?.msg||data?.error_description||`Erreur ${response.status}`);return data}
async function api(table,select='*'){return request(`/rest/v1/${table}?select=${encodeURIComponent(select)}`)}
async function authApi(table,select='*',filters=''){return request(`/rest/v1/${table}?select=${encodeURIComponent(select)}${filters}`,{auth:true})}

function loginScreen(message=''){app.innerHTML=`<div class="login">${brandMark()}<div class="login-intro"><span>ESPACE ÉQUIPE</span><h1>Bienvenue</h1><p>Connectez-vous pour accéder à votre espace de travail.</p></div>${message?`<div class="login-error">${esc(message)}</div>`:''}<form onsubmit="login(event)"><label for="email">Adresse email</label><input id="email" type="email" autocomplete="username" placeholder="nom@parfumeriesam.com" required><label for="password">Mot de passe</label><input id="password" type="password" autocomplete="current-password" required><button class="primary" type="submit">Se connecter</button></form><small class="poc-note">Accès sécurisé · Parfumerie SAM</small></div>`}
function recoverySession(){const params=new URLSearchParams(location.hash.replace(/^#/,'')),type=params.get('type'),token=params.get('access_token');return ['invite','recovery'].includes(type)&&token?{type,token}:null}
function passwordSetupScreen(session,message=''){app.innerHTML=`<div class="login">${brandMark()}<div class="login-intro"><span>ACCÈS SÉCURISÉ</span><h1>Choisir un mot de passe</h1><p>${session.type==='invite'?'Votre invitation est valide.':'Créez votre nouveau mot de passe.'}</p></div>${message?`<div class="login-error">${esc(message)}</div>`:''}<form onsubmit="saveNewPassword(event,'${esc(session.token)}')"><label for="new-password">Nouveau mot de passe</label><input id="new-password" type="password" autocomplete="new-password" minlength="10" required><label for="confirm-password">Confirmer le mot de passe</label><input id="confirm-password" type="password" autocomplete="new-password" minlength="10" required><button class="primary" type="submit">Enregistrer et me connecter</button></form></div>`}
async function saveNewPassword(event,token){event.preventDefault();const password=document.getElementById('new-password').value,confirmPassword=document.getElementById('confirm-password').value;if(password!==confirmPassword)return passwordSetupScreen({type:'recovery',token},'Les deux mots de passe sont différents.');try{await request('/auth/v1/user',{method:'PUT',body:{password},headers:{Authorization:`Bearer ${token}`}});accessToken=token;sessionStorage.setItem('bm_access_token',accessToken);history.replaceState(null,'',location.pathname+location.search);await loadCurrentUser();home();void loadCatalog()}catch(e){passwordSetupScreen({type:'recovery',token},e.message)}}
function disabledAccountScreen(){currentUser=null;accessToken='';sessionStorage.removeItem('bm_access_token');app.innerHTML=`<div class="login">${brandMark()}<div class="login-intro"><span>ACCÈS SUSPENDU</span><h1>Compte désactivé</h1><p>Votre accès a été désactivé. Contactez votre administrateur.</p></div><button class="primary" onclick="loginScreen()">Retour à la connexion</button></div>`}

async function login(event){event.preventDefault();const button=event.submitter;button.disabled=true;button.textContent='Connexion…';try{const data=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email:document.querySelector('#email').value.trim(),password:document.querySelector('#password').value}});accessToken=data.access_token;sessionStorage.setItem('bm_access_token',accessToken);await loadCurrentUser();home();void loadCatalog()}catch(error){const disabled=error.message==='COMPTE_DESACTIVE';accessToken='';currentUser=null;sessionStorage.removeItem('bm_access_token');if(disabled)disabledAccountScreen();else loginScreen('Email ou mot de passe incorrect, ou compte non relié.')}}

async function loadCurrentUser(){if(!accessToken)throw new Error('Session absente');const authUser=await request('/auth/v1/user',{auth:true});const users=await authApi('utilisateurs','user_id,nom,prenom,nom_famille,civilite,email,telephone,actif',`&auth_user_id=eq.${encodeURIComponent(authUser.id)}`);if(users.length!==1)throw new Error('Compte non relié');const user=users[0];if(user.actif!==true)throw new Error('COMPTE_DESACTIVE');const assignments=await authApi('utilisateurs_roles_sites','role_id,site_id',`&user_id=eq.${encodeURIComponent(user.user_id)}&actif=eq.true`);const [roles,sites]=await Promise.all([authApi('roles','role_id,code_role','&actif=eq.true'),authApi('sites','site_id,nom_site','&actif=eq.true')]);const roleById=Object.fromEntries(roles.map(role=>[role.role_id,role.code_role])),siteById=Object.fromEntries(sites.map(site=>[site.site_id,site.nom_site]));currentUser={...user,nom:user.prenom||user.nom,contactEmail:user.email||'',email:authUser.email,assignments:assignments.filter(item=>roleById[item.role_id]&&(!item.site_id||siteById[item.site_id])).map(item=>({role:roleById[item.role_id],siteId:item.site_id,site:item.site_id?siteById[item.site_id]:'GLOBAL'}))};return currentUser}

function logout(){accessToken='';currentUser=null;sessionStorage.removeItem('bm_access_token');loginScreen()}
async function boot(){const recovery=recoverySession();if(recovery){passwordSetupScreen(recovery);return}if(!accessToken){loginScreen();return}try{await loadCurrentUser();home();void loadCatalog()}catch(error){if(error.message==='COMPTE_DESACTIVE')disabledAccountScreen();else logout()}}

async function loadCatalog(){try{const [brands,categories,items,references]=await Promise.all([api('marques','marque_id,nom_marque,actif'),api('categories_produits','categorie_produit_id,nom_categorie,actif'),api('produits','produit_id,nom_produit,variante,marque_id,categorie_produit_id,actif'),api('references_produit','reference_produit_id,produit_id,libelle_reference,actif')]);const brandById=Object.fromEntries(brands.filter(x=>x.actif).map(x=>[x.marque_id,x.nom_marque])),categoryById=Object.fromEntries(categories.filter(x=>x.actif).map(x=>[x.categorie_produit_id,x.nom_categorie]));products=items.filter(x=>x.actif&&brandById[x.marque_id]).map(product=>({id:product.produit_id,name:product.nom_produit,variant:product.variante||'',brand:brandById[product.marque_id],category:categoryById[product.categorie_produit_id]||'Autres',emoji:'🧴',refs:references.filter(ref=>ref.actif&&ref.produit_id===product.produit_id).map(ref=>({id:ref.reference_produit_id,label:ref.libelle_reference}))})).filter(product=>product.refs.length).sort((a,b)=>(a.brand+' '+a.name).localeCompare(b.brand+' '+b.name,'fr'));catalogReady=true}catch(error){console.error(error);catalogReady=false}}

function profile(){const contact=currentUser.contactEmail||currentUser.email,phone=currentUser.telephone||'À compléter par l’Administrateur';shell(`<div class="title"><small>MON PROFIL</small><h1>${esc(currentUser.nom)}</h1><p>${esc(contact)} · ${esc(phone)}</p></div><section class="list">${currentUser.assignments.map(assignment=>`<article class="product-row"><div class="grow"><strong>${esc(humanRole(assignment.role))}</strong><span>${esc(assignment.site)}</span></div></article>`).join('')}</section><button class="primary secondary" onclick="logout()">Se déconnecter</button>`,'home()')}
function removeItem(index){cart.splice(index,1);pendingRequestOperationId=null;review()}
