const app=document.querySelector('#app');
const SUPABASE_URL='https://cvaysurwzkphmsvqujab.supabase.co';
const SUPABASE_KEY='sb_publishable_EvO6xjIFQH74h-p7hXLQ-Q_oEmvcWCo';
const REAPPRO_TYPE='1f51c270-d2f1-4ea0-a22d-5a70579b6e7b',BOUTIQUE104_HOLDER='74933c6f-bbe0-46de-b41d-d3f116a6d5e8',DEPOT_HOLDER='6a22c3ab-7618-4c6a-bd03-c3bc21c1455f';
let cart=[],products=[],catalogReady=false,currentUser=null,accessToken=sessionStorage.getItem('bm_access_token')||'',pendingRequestOperationId=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function request(path,{method='GET',body,auth=false,headers:extra={}}={}){const headers={apikey:SUPABASE_KEY,'Content-Type':'application/json',...extra};if(auth&&accessToken)headers.Authorization=`Bearer ${accessToken}`;const r=await fetch(`${SUPABASE_URL}${path}`,{method,headers,body:body?JSON.stringify(body):undefined});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.msg||data?.error_description||`Erreur ${r.status}`);return data}
async function api(table,select='*'){return request(`/rest/v1/${table}?select=${encodeURIComponent(select)}`)}
async function authApi(table,select='*',filters=''){return request(`/rest/v1/${table}?select=${encodeURIComponent(select)}${filters}`,{auth:true})}
function loginScreen(message=''){app.innerHTML=`<div class="login"><small>BOUTIQUE MANAGER</small><h1>Connexion</h1><p>Connectez-vous avec votre compte de test.</p>${message?`<div class="login-error">${esc(message)}</div>`:''}<form onsubmit="login(event)"><label>Email</label><input id="email" type="email" autocomplete="username" placeholder="georges@example.com" required><label>Mot de passe</label><input id="password" type="password" autocomplete="current-password" required><button class="primary" type="submit">Se connecter</button></form><small class="poc-note">POC · Georges et Joel peuvent être testés séparément.</small></div>`}
async function login(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Connexion…';try{const data=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email:document.querySelector('#email').value.trim(),password:document.querySelector('#password').value}});accessToken=data.access_token;sessionStorage.setItem('bm_access_token',accessToken);await loadCurrentUser();home();loadCatalog()}catch(err){accessToken='';sessionStorage.removeItem('bm_access_token');loginScreen('Email ou mot de passe incorrect, ou compte non relié.')}}
async function loadCurrentUser(){if(!accessToken)throw new Error('Session absente');const me=await request('/auth/v1/user',{auth:true});const users=await authApi('utilisateurs','user_id,nom',`&auth_user_id=eq.${encodeURIComponent(me.id)}`);if(users.length!==1)throw new Error('Compte non relié');const u=users[0];const assignments=await authApi('utilisateurs_roles_sites','role_id,site_id',`&user_id=eq.${encodeURIComponent(u.user_id)}`);const [roles,sites]=await Promise.all([authApi('roles','role_id,code_role'),authApi('sites','site_id,nom_site')]);const rm=Object.fromEntries(roles.map(r=>[r.role_id,r.code_role])),sm=Object.fromEntries(sites.map(s=>[s.site_id,s.nom_site]));currentUser={...u,email:me.email,assignments:assignments.map(a=>({role:rm[a.role_id]||'RÔLE',siteId:a.site_id,site:a.site_id?(sm[a.site_id]||'Site'):'GLOBAL'}))};return currentUser}
function logout(){accessToken='';currentUser=null;sessionStorage.removeItem('bm_access_token');loginScreen()}
async function boot(){if(!accessToken){loginScreen();return}try{await loadCurrentUser();home();loadCatalog()}catch(e){logout()}}
async function loadCatalog(){try{const [brands,categories,prods,refs]=await Promise.all([api('marques','marque_id,nom_marque,actif'),api('categories_produits','categorie_produit_id,nom_categorie,actif'),api('produits','produit_id,nom_produit,variante,marque_id,categorie_produit_id,actif'),api('references_produit','reference_produit_id,produit_id,libelle_reference,actif')]);const bm=Object.fromEntries(brands.filter(x=>x.actif).map(x=>[x.marque_id,x.nom_marque])),cm=Object.fromEntries(categories.filter(x=>x.actif).map(x=>[x.categorie_produit_id,x.nom_categorie]));products=prods.filter(x=>x.actif&&bm[x.marque_id]).map(p=>({id:p.produit_id,name:p.nom_produit,variant:p.variante||'',brand:bm[p.marque_id],category:cm[p.categorie_produit_id]||'Autres',emoji:'🧴',refs:refs.filter(r=>r.actif&&r.produit_id===p.produit_id).map(r=>({id:r.reference_produit_id,label:r.libelle_reference}))})).filter(p=>p.refs.length).sort((a,b)=>(a.brand+' '+a.name).localeCompare(b.brand+' '+b.name,'fr'));catalogReady=true}catch(e){console.error(e);catalogReady=false}}
function primarySite(){return currentUser?.assignments.find(a=>a.site!=='GLOBAL')?.site||'Accès global'}
function canRequestFromBoutique104(){return currentUser?.assignments.some(a=>a.site==='Boutique 104'&&['GERANT','VENDEUR','PATRON'].includes(a.role))}
function isDepotStorekeeper(){return currentUser?.assignments.some(a=>a.site==='Dépôt Marché Central'&&a.role==='MAGASINIER')}
function shell(content,back=''){const initial=esc((currentUser?.nom||'?').charAt(0).toUpperCase());app.innerHTML=`<header>${back?`<button class="back" onclick="${back}">←</button>`:`<div><small>BOUTIQUE MANAGER</small><h1>Bonjour ${esc(currentUser?.nom)} 👋</h1><p>${esc(primarySite())}</p></div><button class="avatar" onclick="profile()">${initial}</button>`}</header>${content}`}
function home(){const depot=isDepotStorekeeper();shell(`<section class="hero"><span>Session sécurisée</span><strong>${esc(currentUser.assignments.map(a=>a.role).join(' · '))}</strong><button onclick="profile()">Voir mon profil →</button></section><h2>Que voulez-vous faire ?</h2><section class="grid">${depot?`<button class="card" onclick="requestsInbox()"><b>📥</b><span>Demandes à traiter</span><small>Demandes adressées au dépôt</small></button>`:`<button class="card" onclick="startRequest()"><b>＋</b><span>Demander du stock</span><small>Créer une demande au dépôt</small></button>`}<button class="card"><b>🚚</b><span>Réceptions</span><small>Contrôler les arrivages</small></button><button class="card" onclick="catalog()"><b>📦</b><span>Catalogue</span><small>Produits et catégories</small></button><button class="card"><b>↔</b><span>Flux stock</span><small>Suivre les mouvements</small></button></section>${nav()}`)}
function profile(){shell(`<div class="title"><small>MON PROFIL</small><h1>${esc(currentUser.nom)}</h1><p>${esc(currentUser.email)}</p></div><section class="list">${currentUser.assignments.map(a=>`<article class="product-row"><div class="grow"><strong>${esc(a.role)}</strong><span>${esc(a.site)}</span></div></article>`).join('')}</section><button class="primary secondary" onclick="logout()">Se déconnecter</button>`,'home()')}
function nav(){return `<nav><button class="active" onclick="home()">⌂<span>Accueil</span></button><button>▣<span>Stock</span></button><button>↔<span>Flux</span></button><button onclick="profile()">◉<span>Profil</span></button></nav>`}
async function requestsInbox(){if(!isDepotStorekeeper()){shell(`<div class="title"><small>SÉCURITÉ</small><h1>Accès non autorisé</h1><p>Cette vue est réservée au magasinier du Dépôt Marché Central.</p></div>`,'home()');return}shell(`<div class="title"><small>MAGASINIER</small><h1>Demandes à traiter</h1><p>Chargement sécurisé depuis Supabase…</p></div>`,'home()');try{const flows=await authApi('flux_stock','flux_stock_id,demandeur_user_id,statut,cree_le,detenteur_source_id,detenteur_destination_id',`&detenteur_source_id=eq.${DEPOT_HOLDER}&statut=eq.DEMANDE&order=cree_le.asc`);if(!flows.length){shell(`<div class="title"><small>MAGASINIER</small><h1>Demandes à traiter</h1><p>Aucune demande en attente.</p></div><div class="empty">Tout est à jour.</div>`,'home()');return}const requesterIds=[...new Set(flows.map(f=>f.demandeur_user_id))];const users=await authApi('utilisateurs','user_id,nom',`&user_id=in.(${requesterIds.join(',')})`);const names=Object.fromEntries(users.map(u=>[u.user_id,u.nom]));shell(`<div class="title"><small>MAGASINIER · DÉPÔT MARCHÉ CENTRAL</small><h1>Demandes à traiter</h1><p>${flows.length} demande${flows.length>1?'s':''} en attente</p></div><section class="list">${flows.map(f=>`<article class="product-row"><div class="grow"><small>${esc(new Date(f.cree_le).toLocaleString('fr-FR'))}</small><strong>${esc(names[f.demandeur_user_id]||'Demandeur')} · Boutique 104</strong><span>Statut : ${esc(f.statut)}</span></div><button onclick="requestDetail('${f.flux_stock_id}')">→</button></article>`).join('')}</section>`,'home()')}catch(err){shell(`<div class="title"><small>ERREUR</small><h1>Demandes indisponibles</h1><p>${esc(err.message)}</p></div><button class="primary" onclick="requestsInbox()">Réessayer</button>`,'home()')}}
async function requestDetail(id){shell(`<div class="title"><small>DEMANDE</small><h1>Chargement…</h1></div>`,'requestsInbox()');try{const flows=await authApi('flux_stock','flux_stock_id,demandeur_user_id,statut,cree_le',`&flux_stock_id=eq.${encodeURIComponent(id)}`);if(flows.length!==1)throw new Error('Demande inaccessible');const f=flows[0];const lines=await authApi('lignes_flux_stock','ligne_flux_stock_id,reference_produit_id,quantite_demandee',`&flux_stock_id=eq.${encodeURIComponent(id)}`);const refIds=[...new Set(lines.map(l=>l.reference_produit_id))];const refs=refIds.length?await request(`/rest/v1/references_produit?select=reference_produit_id,libelle_reference&reference_produit_id=in.(${refIds.join(',')})`):[];const rm=Object.fromEntries(refs.map(r=>[r.reference_produit_id,r.libelle_reference]));shell(`<div class="title"><small>DEMANDE ${esc(id.slice(0,8))}</small><h1>Boutique 104</h1><p>${esc(new Date(f.cree_le).toLocaleString('fr-FR'))} · ${esc(f.statut)}</p></div><section class="list">${lines.map(l=>`<article class="product-row"><div class="grow"><strong>${esc(rm[l.reference_produit_id]||'Référence')}</strong><span>Quantité demandée : ${l.quantite_demandee}</span></div></article>`).join('')}</section><div class="empty">Lecture seulement pour cette étape. Les boutons Accepter / Modifier / Refuser seront sécurisés à l'étape suivante.</div>`,'requestsInbox()')}catch(err){shell(`<div class="title"><small>ERREUR</small><h1>Demande inaccessible</h1><p>${esc(err.message)}</p></div>`,'requestsInbox()')}}
async function startRequest(){if(!canRequestFromBoutique104()){shell(`<div class="title"><small>DEMANDE STOCK</small><h1>Action non disponible ici</h1><p>Ce premier scénario POC crée les demandes de Boutique 104 vers le Dépôt Marché Central.</p></div>`,'home()');return}pendingRequestOperationId=null;shell(`<div class="title"><small>NOUVELLE DEMANDE</small><h1>Chargement du catalogue…</h1><p>Lecture depuis Supabase.</p></div>`,'home()');if(!catalogReady)await loadCatalog();if(!catalogReady){shell(`<div class="title"><small>NOUVELLE DEMANDE</small><h1>Catalogue indisponible</h1></div><button class="primary" onclick="startRequest()">Réessayer</button>`,'home()');return}renderRequest()}
function renderRequest(){const cats=[...new Set(products.map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'fr'));shell(`<div class="title"><small>NOUVELLE DEMANDE</small><h1>Choisir les produits</h1><p>${products.length} produits · Boutique 104 → Dépôt Marché Central</p></div><div class="search">⌕ <input placeholder="Rechercher un produit…" oninput="filterProducts(this.value)"></div><div class="chips"><button class="selected" onclick="filterCategory('')">Tous</button>${cats.map((c,i)=>`<button onclick="filterCategoryByIndex(${i})">${esc(c)}</button>`).join('')}</div><section id="products" class="list">${productRows(products)}</section><button class="basket" onclick="review()">Voir la demande <span>${cart.length}</span></button>`,'home()')}
function catalog(){startRequest()}
function productRows(items){return items.map(p=>`<article class="product-row"><div class="photo">${p.emoji}</div><div class="grow"><small>${esc(p.brand)} · ${esc(p.category)}</small><strong>${esc(p.name)}</strong>${p.variant?`<span>${esc(p.variant)}</span>`:''}<span>${p.refs.length} référence${p.refs.length>1?'s':''}</span></div><button onclick="choose('${p.id}')">＋</button></article>`).join('')||'<div class="empty">Aucun produit trouvé.</div>'}
function filterProducts(q){document.querySelector('#products').innerHTML=productRows(products.filter(p=>(p.brand+' '+p.name+' '+p.variant+' '+p.category).toLowerCase().includes(q.toLowerCase())))}
function filterCategory(c){document.querySelector('#products').innerHTML=productRows(c?products.filter(p=>p.category===c):products)}
function filterCategoryByIndex(i){const cats=[...new Set(products.map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'fr'));filterCategory(cats[i])}
function choose(id){const p=products.find(x=>x.id===id);shell(`<div class="title"><small>${esc(p.brand)}</small><h1>${esc(p.name)}</h1><p>${esc(p.variant||p.category)}</p></div><div class="big-photo">${p.emoji}</div><label>Référence</label><select id="ref">${p.refs.map(r=>`<option value="${r.id}">${esc(r.label)}</option>`).join('')}</select><label>Quantité demandée</label><div class="qty"><button onclick="qty(-1)">−</button><strong id="qty">1</strong><button onclick="qty(1)">＋</button></div><button class="primary" onclick="add('${id}')">Ajouter à la demande</button>`,'renderRequest()')}
function qty(n){const e=document.querySelector('#qty');e.textContent=Math.max(1,+e.textContent+n)}
function add(id){const p=products.find(x=>x.id===id),sel=document.querySelector('#ref'),r=p.refs.find(x=>x.id===sel.value),existing=cart.find(x=>x.referenceId===r.id);if(existing)existing.qty+=+document.querySelector('#qty').textContent;else cart.push({referenceId:r.id,brand:p.brand,name:p.name,ref:r.label,qty:+document.querySelector('#qty').textContent});pendingRequestOperationId=null;renderRequest()}
function review(){shell(`<div class="title"><small>RÉCAPITULATIF</small><h1>Ma demande</h1><p>Boutique 104 → Dépôt Marché Central</p></div>${cart.length?`<section class="list">${cart.map((x,i)=>`<article class="product-row"><div class="grow"><small>${esc(x.brand)}</small><strong>${esc(x.name)}</strong><span>${esc(x.ref)} · Quantité ${x.qty}</span></div><button onclick="removeItem(${i})">×</button></article>`).join('')}</section><button id="sendBtn" class="primary" onclick="sent()">Envoyer la demande</button>`:`<div class="empty">Votre demande est vide.</div><button class="primary" onclick="renderRequest()">Ajouter des produits</button>`}`,'renderRequest()')}
function removeItem(i){cart.splice(i,1);pendingRequestOperationId=null;review()}
async function sent(){if(!cart.length)return;const btn=document.querySelector('#sendBtn');if(btn){btn.disabled=true;btn.textContent='Envoi sécurisé…'}if(!pendingRequestOperationId)pendingRequestOperationId=crypto.randomUUID();try{const fluxId=await request('/rest/v1/rpc/creer_demande_stock',{method:'POST',auth:true,body:{p_operation_client_id:pendingRequestOperationId,p_detenteur_source_id:DEPOT_HOLDER,p_detenteur_destination_id:BOUTIQUE104_HOLDER,p_lignes:cart.map(x=>({reference_produit_id:x.referenceId,quantite:x.qty}))}});cart=[];pendingRequestOperationId=null;shell(`<div class="success"><div>✓</div><h1>Demande envoyée</h1><p>La demande et toutes ses lignes ont été enregistrées en une seule opération. Identifiant : ${esc(String(fluxId).slice(0,8))}…</p><button class="primary" onclick="home()">Retour à l'accueil</button></div>`)}catch(err){console.error(err);shell(`<div class="title"><small>ENVOI À RÉESSAYER</small><h1>La demande n'est pas confirmée</h1><p>${esc(err.message)}</p><p>Le même identifiant d'opération sera réutilisé au prochain essai afin d'éviter un doublon.</p></div><button class="primary" onclick="review()">Réessayer</button>`,'home()')}}
boot();