let packagingByRef={};
function normText(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
async function ensurePackaging(){if(Object.keys(packagingByRef).length)return;try{const rows=await api('conditionnements_reference','reference_produit_id,nom_conditionnement,multiplicateur,actif');rows.filter(x=>x.actif).forEach(x=>{(packagingByRef[x.reference_produit_id]??=[]).push(x)});Object.values(packagingByRef).forEach(a=>a.sort((x,y)=>x.multiplicateur-y.multiplicateur))}catch(e){console.error(e)}}
function searchableProduct(p){return normText([p.brand,p.name,p.variant,p.category,...p.refs.map(r=>r.label)].join(' '))}
function catalogPhoto(url,fallback,className=''){return url?`<img class="${className}" src="${esc(url)}" alt="" loading="lazy">`:fallback}
function catalogRows(items){return items.map(p=>`<article class="product-row catalog-row"><div class="photo">${catalogPhoto(p.photo,p.emoji)}</div><div class="grow"><small>${esc(p.brand)}</small><strong>${esc(p.name)}</strong>${p.variant?`<span>${esc(p.variant)}</span>`:''}<span>${esc(p.refs.map(r=>r.label.match(/(\d+\s*(?:ml|mL|g))/)?.[1]).filter(Boolean).join(' · ')||p.category)}</span></div><button aria-label="Voir" onclick="catalogProduct('${p.id}')">→</button></article>`).join('')||'<div class="empty">Aucun produit trouvé.</div>'}
async function catalog(){if(!catalogReady)await loadCatalog();await ensurePackaging();const cats=[...new Set(products.map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'fr'));shell(`<div class="title"><small>PRODUITS</small><h1>Trouver un produit</h1><p>Recherchez par marque, nom, variante ou format.</p></div><div class="search">⌕ <input id="catalog-search" autocomplete="off" placeholder="Ex. Mixa, savon, amande, 400 ml…" oninput="catalogFilter(this.value)"></div><div class="chips"><button class="selected" onclick="catalogCategory('')">Tous</button>${cats.map((c,i)=>`<button onclick="catalogCategoryIndex(${i})">${esc(c)}</button>`).join('')}</div><section id="catalog-results" class="list">${catalogRows(products)}</section>${nav('products')}`,'home()')}
function catalogFilter(q){const n=normText(q);const words=n.split(' ').filter(Boolean);const found=!n?products:products.filter(p=>{const hay=searchableProduct(p);return words.every(w=>hay.includes(w))});document.querySelector('#catalog-results').innerHTML=catalogRows(found)}
function catalogCategory(c){document.querySelector('#catalog-results').innerHTML=catalogRows(c?products.filter(p=>p.category===c):products)}
function catalogCategoryIndex(i){const cats=[...new Set(products.map(p=>p.category))].sort((a,b)=>a.localeCompare(b,'fr'));catalogCategory(cats[i])}
function packLabel(x){if(x.nom_conditionnement==='Carton')return `Carton (${x.multiplicateur})`;return x.nom_conditionnement}
function catalogProduct(id){const p=products.find(x=>x.id===id);if(!p)return catalog();shell(`<div class="title"><small>${esc(p.brand)}</small><h1>${esc(p.name)}</h1><p>${esc(p.variant||p.category)}</p>${p.manufacturer?`<p class="product-manufacturer">Fabriqué par <strong>${esc(p.manufacturer)}</strong></p>`:''}</div><div class="big-photo">${catalogPhoto(p.photo,p.emoji)}</div><section class="list">${p.refs.map(r=>{const packs=packagingByRef[r.id]||[];return `<article class="pack-card reference-card">${r.photo?`<img class="reference-photo" src="${esc(r.photo)}" alt="Photo de ${esc(r.label)}" loading="lazy">`:''}<div><strong>${esc(r.label)}</strong><small>Conditionnements disponibles</small><div class="pack-options">${packs.map(x=>`<span>${esc(packLabel(x))}</span>`).join('')||'<em>À renseigner</em>'}</div></div></article>`}).join('')}</section>`,'catalog()')}
