const inboxBeforeConfirm=requestsInbox;
requestsInbox=async function(){
 if(!isDepotStorekeeper())return inboxBeforeConfirm();
 shell(`<div class="title"><small>MAGASINIER</small><h1>Demandes à traiter</h1><p>Chargement…</p></div>`,'home()');
 try{const flows=await authApi('flux_stock','flux_stock_id,statut,cree_le',`&detenteur_source_id=eq.${DEPOT_HOLDER}&statut=in.(DEMANDE,EN_TRAITEMENT,A_CONFIRMER_MAGASINIER)&order=cree_le.asc`);if(!flows.length){shell(`<div class="title"><small>MAGASINIER</small><h1>Demandes à traiter</h1></div><div class="empty">Aucune action en attente. Tout est à jour.</div>`,'home()');return}const confirm=flows.filter(f=>f.statut==='A_CONFIRMER_MAGASINIER');const active=flows.filter(f=>f.statut!=='A_CONFIRMER_MAGASINIER');shell(`<div class="title"><small>MAGASINIER</small><h1>Demandes à traiter</h1></div>${confirm.length?`<h2>⚠️ Réceptions à vérifier (${confirm.length})</h2><section class="list">${confirm.map(f=>`<article class="product-row"><div class="grow"><strong>Demande ${esc(f.flux_stock_id.slice(0,8))}</strong><span>Boutique 104 a déclaré sa réception</span></div><button onclick="confirmationDetail('${f.flux_stock_id}')">Vérifier</button></article>`).join('')}</section>`:''}${active.length?`<h2>🚚 En traitement (${active.length})</h2><section class="list">${active.map(f=>`<article class="product-row"><div class="grow"><strong>Demande ${esc(f.flux_stock_id.slice(0,8))}</strong><span>${esc(f.statut)}</span></div><button onclick="requestDetail('${f.flux_stock_id}')">Ouvrir</button></article>`).join('')}</section>`:''}`,'home()')}catch(e){shell(`<div class="title"><small>ERREUR</small><h1>Demandes indisponibles</h1><p>${esc(e.message)}</p></div>`,'home()')}
}
async function confirmationDetail(id){
 shell(`<div class="title"><small>CONFIRMATION</small><h1>Chargement…</h1></div>`,'requestsInbox()');
 try{const lines=await authApi('lignes_flux_stock','ligne_flux_stock_id,reference_produit_id',`&flux_stock_id=eq.${encodeURIComponent(id)}`);if(lines.length!==1)throw new Error('Ce test POC attend une seule ligne.');const l=lines[0];const refs=await request(`/rest/v1/references_produit?select=libelle_reference&reference_produit_id=eq.${l.reference_produit_id}`);const events=await authApi('evenements_lignes_flux_stock','type_evenement,quantite,decision',`&ligne_flux_stock_id=eq.${l.ligne_flux_stock_id}&type_evenement=in.(DECISION_MAGASINIER,DECLARATION_RECEPTION)`);const d=events.find(e=>e.type_evenement==='DECISION_MAGASINIER');const r=events.find(e=>e.type_evenement==='DECLARATION_RECEPTION');const same=d&&r&&d.quantite===r.quantite;const diff=(r?.quantite??0)-(d?.quantite??0);shell(`<div class="title"><small>DEMANDE ${esc(id.slice(0,8))}</small><h1>${same?'Confirmer la réception':'⚠️ Écart à traiter'}</h1><p>Dépôt Marché Central → Boutique 104</p></div><section class="list"><article class="product-row"><div class="grow"><strong>${esc(refs[0]?.libelle_reference||'Référence')}</strong><span>Quantité expédiée : <b>${d?.quantite??'?'}</b></span><span>Quantité déclarée reçue : <b>${r?.quantite??'?'}</b></span><span>${same?'✓ Les quantités correspondent':`⚠️ Écart : <b>${diff>0?'+':''}${diff}</b>`}</span></div></article></section>${same?`<button class="primary" onclick="confirmReception('${id}')">✓ Confirmer et clôturer</button>`:`<label>Motif / observation du magasinier</label><input id="discrepancyComment" maxlength="300" placeholder="Ex. J’ai bien expédié 2 unités"><button class="primary" onclick="contestReception('${id}')">⚠️ Signaler l’anomalie</button><div class="empty">Cette action ne modifie ni l’expédition ni la déclaration de Georges. Elle ajoute une contestation à l’historique et place le flux en anomalie.</div>`}`,'requestsInbox()')}catch(e){shell(`<div class="title"><small>ERREUR</small><h1>Confirmation inaccessible</h1><p>${esc(e.message)}</p></div>`,'requestsInbox()')}
}
async function confirmReception(id){if(!confirm('Confirmer que la réception correspond à l’expédition et clôturer ce flux ?'))return;try{await request('/rest/v1/rpc/confirmer_reception_stock',{method:'POST',auth:true,body:{p_flux_stock_id:id,p_commentaire:'Réception conforme confirmée par le magasinier'}});shell(`<div class="success"><div>✓</div><h1>Flux clôturé</h1><p>Joel a confirmé la réception. Le transfert est terminé et son historique reste conservé.</p><button class="primary" onclick="home()">Retour à l’accueil</button></div>`)}catch(e){shell(`<div class="title"><small>CONFIRMATION REFUSÉE</small><h1>Aucun changement enregistré</h1><p>${esc(e.message)}</p></div><button class="primary" onclick="confirmationDetail('${id}')">Retour</button>`,'requestsInbox()')}
}
async function contestReception(id){const comment=document.querySelector('#discrepancyComment')?.value?.trim();if(!comment){alert('Indique le motif ou l’observation de Joel.');return}if(!confirm('Signaler cet écart comme anomalie ? Les événements précédents resteront inchangés.'))return;try{await request('/rest/v1/rpc/contester_reception_stock',{method:'POST',auth:true,body:{p_flux_stock_id:id,p_commentaire:comment}});shell(`<div class="success"><div>⚠️</div><h1>Anomalie enregistrée</h1><p>L’écart est maintenant officiellement signalé. L’expédition et la déclaration de réception restent conservées séparément dans l’historique.</p><button class="primary" onclick="home()">Retour à l’accueil</button></div>`)}catch(e){shell(`<div class="title"><small>ANOMALIE NON ENREGISTRÉE</small><h1>Aucun historique modifié</h1><p>${esc(e.message)}</p></div><button class="primary" onclick="confirmationDetail('${id}')">Retour</button>`,'requestsInbox()')}
}
