// Traitement des flux existants. Les quantités affichées proviennent des événements
// métier autorisés ; la table comptable mouvements_stock n'est jamais exposée au client.
function stockOpId(key){const k='bm_stock_op_'+key;let v=sessionStorage.getItem(k);if(!v){v=crypto.randomUUID();sessionStorage.setItem(k,v)}return v}
function clearStockOpId(key){sessionStorage.removeItem('bm_stock_op_'+key)}
function flowHumanStatus(s){return ({DEMANDE:'Nouvelle demande',EN_TRAITEMENT:'À préparer',EN_TRANSIT:'En transit',CONTROLE_DEMANDEUR:'Contrôle effectué',A_CONFIRMER_MAGASINIER:'À confirmer',RECEPTIONNE:'Réceptionné',CLOTURE:'Clôturé',REFUSE:'Refusé',ANOMALIE:'Anomalie'})[s]||s}
function flowHumanType(code){return code==='RETOUR'?'Retour':code==='TRANSFERT'?'Transfert':'Réapprovisionnement'}
async function flowContextData(){const holder=await contextHolder();if(!holder)throw new Error('Aucun stock n’est associé à ce site.');const types=await authApi('types_flux_stock','type_flux_stock_id,code_type_flux,nom_type_flux'),tm=Object.fromEntries(types.map(t=>[t.type_flux_stock_id,t]));return {holder,tm}}
async function enrichFlowPlaces(flows){if(!flows.length)return flows;const labels=await accessibleHolderLabels();return flows.map(f=>({...f,sourceName:labels[f.detenteur_source_id]||'Source',destinationName:labels[f.detenteur_destination_id]||'Destination'}))}
async function operationalInbox(mode='requests'){
  const context=currentContext();
  if(!['SITE','MOBILE'].includes(context.kind))return;
  const isMag=hasRoleHere('MAGASINIER'),isDestocker=hasRoleHere('DESTOCKEUR');
  const allowed=(isMag&&['requests','returns','confirmations','receipts'].includes(mode))||(isDestocker&&['outgoing','confirmations','receipts'].includes(mode))||(!isMag&&!isDestocker&&mode==='receipts');
  if(!allowed){shell(`<div class="title"><small>SÉCURITÉ</small><h1>Action non disponible ici</h1><p>Ce flux ne correspond pas à votre rôle dans cet espace.</p></div>`,'home()');return}
  shell(`<div class="title"><small>${esc(context.name)}</small><h1>Chargement…</h1></div>`,'home()');
  try{
    const {holder,tm}=await flowContextData();
    let filter='';
    if(['requests','outgoing'].includes(mode))filter=`&detenteur_source_id=eq.${holder.detenteur_stock_id}&statut=in.(DEMANDE,EN_TRAITEMENT)`;
    else if(mode==='returns')filter=`&detenteur_destination_id=eq.${holder.detenteur_stock_id}&statut=in.(DEMANDE,EN_TRAITEMENT,EN_TRANSIT)`;
    else if(mode==='confirmations')filter=`&detenteur_source_id=eq.${holder.detenteur_stock_id}&statut=eq.A_CONFIRMER_MAGASINIER`;
    else filter=`&detenteur_destination_id=eq.${holder.detenteur_stock_id}&statut=eq.EN_TRANSIT`;
    let flows=await authApi('flux_stock','flux_stock_id,type_flux_stock_id,detenteur_source_id,detenteur_destination_id,demandeur_user_id,statut,cree_le',`${filter}&order=cree_le.asc`);
    if(mode==='requests')flows=flows.filter(f=>tm[f.type_flux_stock_id]?.code_type_flux!=='RETOUR');
    if(['returns','outgoing'].includes(mode))flows=flows.filter(f=>tm[f.type_flux_stock_id]?.code_type_flux==='RETOUR');
    flows=await enrichFlowPlaces(flows);
    const title=mode==='requests'?'Demandes reçues':mode==='outgoing'?'Retours à envoyer':mode==='returns'?'Retours à réceptionner':mode==='confirmations'?'Contrôles à confirmer':'Réceptions';
    if(!flows.length){shell(`<div class="title"><small>${esc(context.name)}</small><h1>${title}</h1><p>Aucune action en attente.</p></div><div class="empty">Tout est à jour.</div>`,'home()');return}
    shell(`<div class="title"><small>${esc(context.name)}</small><h1>${title}</h1><p>${flows.length} flux en attente</p></div><section class="list">${flows.map(f=>{const code=tm[f.type_flux_stock_id]?.code_type_flux;return `<article class="product-row"><div class="grow"><small>${esc(flowHumanType(code))} · ${esc(new Date(f.cree_le).toLocaleString('fr-FR'))}</small><strong>${esc(f.sourceName)} → ${esc(f.destinationName)}</strong><span>${esc(flowHumanStatus(f.statut))}</span></div><button aria-label="Ouvrir ce flux" onclick="operationalFlowDetail('${f.flux_stock_id}','${mode}')">→</button></article>`}).join('')}</section>`,'home()');
  }catch(e){shell(`<div class="title"><small>ERREUR</small><h1>Flux indisponibles</h1><p>${esc(e.message)}</p></div>`,'home()')}
}
async function operationalFlowDetail(id,mode){try{const flows=await authApi('flux_stock','flux_stock_id,type_flux_stock_id,detenteur_source_id,detenteur_destination_id,statut,cree_le',`&flux_stock_id=eq.${encodeURIComponent(id)}`);if(!flows.length)throw new Error('Flux introuvable.');const f=(await enrichFlowPlaces(flows))[0],types=await authApi('types_flux_stock','type_flux_stock_id,code_type_flux',`&type_flux_stock_id=eq.${f.type_flux_stock_id}`),code=types[0]?.code_type_flux,lines=await authApi('lignes_flux_stock','ligne_flux_stock_id,reference_produit_id,quantite_demandee',`&flux_stock_id=eq.${id}`),refIds=[...new Set(lines.map(l=>l.reference_produit_id))],refs=refIds.length?await authApi('references_produit','reference_produit_id,libelle_reference',`&reference_produit_id=in.(${refIds.join(',')})`):[],rm=Object.fromEntries(refs.map(r=>[r.reference_produit_id,r.libelle_reference]));window._activeOperationalFlow={...f,code,lines,rm,mode};let action='';if(['requests','outgoing'].includes(mode)&&['DEMANDE','EN_TRAITEMENT'].includes(f.statut))action=`<button class="primary" onclick="genericProcessFlow('${id}','${mode}')">${mode==='outgoing'?'Préparer ce retour':'Traiter ce flux'}</button>`;if(mode==='returns'&&f.statut==='EN_TRANSIT')action=`<button class="primary" onclick="genericReceiveFlow('${id}','returns')">Contrôler le retour</button>`;if(mode==='receipts'&&f.statut==='EN_TRANSIT')action=`<button class="primary" onclick="genericReceiveFlow('${id}','receipts')">Contrôler la réception</button>`;if(mode==='confirmations'&&f.statut==='A_CONFIRMER_MAGASINIER')action=`<button class="primary" onclick="genericConfirmFlow('${id}')">Vérifier et confirmer</button>`;shell(`<div class="title"><small>${esc(flowHumanType(code))}</small><h1>${esc(flowHumanStatus(f.statut))}</h1><p>${esc(f.sourceName)} → ${esc(f.destinationName)}</p></div><section class="list">${lines.map(l=>`<article class="product-row"><div class="grow"><strong>${esc(rm[l.reference_produit_id]||'Référence')}</strong><span>${l.quantite_demandee} unité${l.quantite_demandee>1?'s':''}</span></div></article>`).join('')}</section>${action}`,'operationalInbox(\''+mode+'\')')}catch(e){shell(`<div class="title"><small>ERREUR</small><h1>Flux inaccessible</h1><p>${esc(e.message)}</p></div>`,'operationalInbox(\''+mode+'\')')}}
async function genericProcessFlow(id,mode='requests'){const f=window._activeOperationalFlow;if(!f||f.flux_stock_id!==id)return operationalFlowDetail(id,mode);try{const events=await authApi('evenements_lignes_flux_stock','ligne_flux_stock_id,type_evenement,quantite,decision',`&ligne_flux_stock_id=in.(${f.lines.map(l=>l.ligne_flux_stock_id).join(',')})&type_evenement=eq.DECISION_MAGASINIER`),em=Object.fromEntries(events.map(e=>[e.ligne_flux_stock_id,e]));shell(`<div class="title"><small>${esc(flowHumanType(f.code))}</small><h1>${mode==='outgoing'?'Préparer les invendus':'Préparer le flux'}</h1><p>${esc(f.sourceName)} → ${esc(f.destinationName)}</p></div><section class="list">${f.lines.map(l=>{const e=em[l.ligne_flux_stock_id];return `<article class="product-row"><div class="grow"><strong>${esc(f.rm[l.reference_produit_id]||'Référence')}</strong><span>Prévu : ${l.quantite_demandee}</span>${e?`<small>Quantité retenue : ${e.quantite}</small>`:`<label>Quantité à envoyer<input id="pq-${l.ligne_flux_stock_id}" type="number" min="0" step="1" value="${l.quantite_demandee}"></label><select id="pd-${l.ligne_flux_stock_id}"><option value="VALIDE">Envoyer tout</option><option value="MODIFIE">Modifier la quantité</option><option value="REFUSE">Ne pas envoyer</option></select><button onclick="saveFlowLineDecision('${id}','${l.ligne_flux_stock_id}',${l.quantite_demandee},'${mode}')">Enregistrer</button>`}</div></article>`}).join('')}</section>${f.lines.every(l=>em[l.ligne_flux_stock_id])?`<button class="primary" onclick="shipGenericFlow('${id}','${mode}')">${mode==='outgoing'?'Expédier les invendus':'Expédier le flux'}</button>`:''}`,'operationalFlowDetail(\''+id+'\',\''+mode+'\')')}catch(e){shell(`<div class="title"><h1>Préparation indisponible</h1><p>${esc(e.message)}</p></div>`,'operationalFlowDetail(\''+id+'\',\''+mode+'\')')}}
async function saveFlowLineDecision(flowId,lineId,asked,mode='requests'){let decision=document.getElementById('pd-'+lineId).value,qty=Number(document.getElementById('pq-'+lineId).value);if(decision==='REFUSE')qty=0;else if(decision==='VALIDE')qty=asked;else if(!Number.isInteger(qty)||qty<=0||qty===asked){alert('Pour modifier, indiquez une quantité entière positive différente de la quantité prévue.');return}try{await request('/rest/v1/rpc/traiter_ligne_stock_idempotent',{method:'POST',auth:true,body:{p_operation_client_id:stockOpId('decision-'+lineId),p_ligne_flux_stock_id:lineId,p_decision:decision,p_quantite:qty,p_commentaire:null}});clearStockOpId('decision-'+lineId);await operationalFlowDetail(flowId,mode);await genericProcessFlow(flowId,mode)}catch(e){alert(e.message)}}
async function shipGenericFlow(id,mode='requests'){if(!confirm(mode==='outgoing'?'Confirmer l’expédition de ces invendus vers la boutique ?':'Confirmer l’expédition de toutes les lignes validées ?'))return;try{await request('/rest/v1/rpc/expedier_flux_stock_idempotent',{method:'POST',auth:true,body:{p_operation_client_id:stockOpId('ship-'+id),p_flux_stock_id:id,p_commentaire:null}});clearStockOpId('ship-'+id);shell(`<div class="success"><div>✓</div><h1>${mode==='outgoing'?'Retour expédié':'Flux expédié'}</h1><p>${mode==='outgoing'?'Votre stock mobile a été débité. Les invendus sont en route vers la boutique.':'Le stock source a été débité et les produits sont maintenant en transit.'}</p><button class="primary" onclick="operationalInbox('${mode}')">Retour</button></div>`)}catch(e){shell(`<div class="title"><h1>Expédition impossible</h1><p>${esc(e.message)}</p></div><button class="primary" onclick="operationalFlowDetail('${id}','${mode}')">Retour</button>`,'home()')}}
async function genericReceiveFlow(id,mode){const f=window._activeOperationalFlow;if(!f||f.flux_stock_id!==id)return operationalFlowDetail(id,mode);try{const decisions=await authApi('evenements_lignes_flux_stock','ligne_flux_stock_id,quantite,decision,type_evenement',`&ligne_flux_stock_id=in.(${f.lines.map(l=>l.ligne_flux_stock_id).join(',')})&type_evenement=eq.DECISION_MAGASINIER`),shipped=Object.fromEntries(decisions.filter(e=>e.decision!=='REFUSE').map(e=>[e.ligne_flux_stock_id,e.quantite])),sent=f.lines.filter(l=>shipped[l.ligne_flux_stock_id]!=null);if(!sent.length)throw new Error('Les quantités expédiées ne sont pas disponibles.');shell(`<div class="title"><small>${esc(flowHumanType(f.code))}</small><h1>Contrôler la réception</h1><p>${esc(f.sourceName)} → ${esc(f.destinationName)}</p></div><section class="list">${sent.map(l=>`<article class="product-row"><div class="grow"><strong>${esc(f.rm[l.reference_produit_id]||'Référence')}</strong><span>Expédié : ${shipped[l.ligne_flux_stock_id]}</span><label>Réellement reçu<input class="gr-line" data-line="${l.ligne_flux_stock_id}" data-shipped="${shipped[l.ligne_flux_stock_id]}" type="number" min="0" step="1" value="${shipped[l.ligne_flux_stock_id]}"></label></div></article>`).join('')}</section><label>Commentaire général (optionnel)<input id="gr-comment" maxlength="300"></label><button class="primary" onclick="submitGenericReception('${id}','${mode}')">Confirmer le contrôle</button>`,'operationalFlowDetail(\''+id+'\',\''+mode+'\')')}catch(e){shell(`<div class="title"><h1>Réception indisponible</h1><p>${esc(e.message)}</p></div>`,'operationalFlowDetail(\''+id+'\',\''+mode+'\')')}}
async function submitGenericReception(id,mode){const inputs=[...document.querySelectorAll('.gr-line')],lines=[];for(const i of inputs){const q=Number(i.value),s=Number(i.dataset.shipped);if(!Number.isInteger(q)||q<0){alert('Chaque quantité reçue doit être un entier positif ou zéro.');return}lines.push({ligne_flux_stock_id:i.dataset.line,quantite_recue:q,decision:q===s?'VALIDE':q===0?'REFUSE':'MODIFIE'})}try{await request('/rest/v1/rpc/recevoir_flux_stock_idempotent',{method:'POST',auth:true,body:{p_operation_client_id:stockOpId('receive-'+id),p_flux_stock_id:id,p_lignes:lines,p_commentaire:document.getElementById('gr-comment').value.trim()||null}});clearStockOpId('receive-'+id);shell(`<div class="success"><div>✓</div><h1>Réception enregistrée</h1><p>Le stock destination a été crédité. Le site source doit maintenant confirmer le contrôle.</p><button class="primary" onclick="operationalInbox('${mode}')">Retour</button></div>`)}catch(e){shell(`<div class="title"><h1>Réception non enregistrée</h1><p>${esc(e.message)}</p></div><button class="primary" onclick="operationalFlowDetail('${id}','${mode}')">Retour</button>`,'home()')}}
async function genericConfirmFlow(id){const f=window._activeOperationalFlow;if(!f||f.flux_stock_id!==id)return operationalFlowDetail(id,'confirmations');try{const events=await authApi('evenements_lignes_flux_stock','ligne_flux_stock_id,quantite,decision,type_evenement',`&ligne_flux_stock_id=in.(${f.lines.map(l=>l.ligne_flux_stock_id).join(',')})&type_evenement=in.(DECISION_MAGASINIER,DECLARATION_RECEPTION)`),decisions=events.filter(e=>e.type_evenement==='DECISION_MAGASINIER'&&e.decision!=='REFUSE'),receipts=events.filter(e=>e.type_evenement==='DECLARATION_RECEPTION'),sentMap=Object.fromEntries(decisions.map(e=>[e.ligne_flux_stock_id,e.quantite])),receivedMap=Object.fromEntries(receipts.map(e=>[e.ligne_flux_stock_id,e.quantite])),sent=f.lines.filter(l=>sentMap[l.ligne_flux_stock_id]!=null);if(!sent.length)throw new Error('L’historique d’expédition n’est pas disponible.');shell(`<div class="title"><small>${esc(flowHumanType(f.code))}</small><h1>Confirmer la réception</h1><p>Comparez ce que vous avez expédié avec ce que la boutique déclare avoir reçu.</p></div><section class="list">${sent.map(l=>{const s=sentMap[l.ligne_flux_stock_id],r=receivedMap[l.ligne_flux_stock_id],ok=s===r;return `<article class="product-row"><div class="grow"><strong>${esc(f.rm[l.reference_produit_id]||'Référence')}</strong><span>Expédié : ${s} · Reçu : ${r??'—'}</span><small>${ok?'✓ Conforme':'⚠ Écart à vérifier'}</small><select class="gc-line" data-line="${l.ligne_flux_stock_id}" data-ok="${ok?'1':'0'}"><option value="CONFIRME" ${ok?'':'disabled'}>Confirmer</option><option value="CONTESTE" ${ok?'':'selected'}>Contester</option></select><input class="gc-comment" data-line="${l.ligne_flux_stock_id}" placeholder="Motif si contestation" maxlength="300"></div></article>`}).join('')}</section><button class="primary" onclick="submitGenericConfirmation('${id}')">Valider la confirmation</button>`,'operationalFlowDetail(\''+id+'\',\'confirmations\')')}catch(e){shell(`<div class="title"><h1>Confirmation indisponible</h1><p>${esc(e.message)}</p></div>`,'operationalFlowDetail(\''+id+'\',\'confirmations\')')}}
async function submitGenericConfirmation(id){const selects=[...document.querySelectorAll('.gc-line')],lines=[];for(const s of selects){const line=s.dataset.line,decision=s.value,c=document.querySelector(`.gc-comment[data-line="${line}"]`)?.value.trim()||null;if(decision==='CONTESTE'&&!c){alert('Indiquez le motif de chaque contestation.');return}lines.push({ligne_flux_stock_id:line,decision,commentaire:c})}try{const result=await request('/rest/v1/rpc/confirmer_flux_stock_idempotent',{method:'POST',auth:true,body:{p_operation_client_id:stockOpId('confirm-'+id),p_flux_stock_id:id,p_lignes:lines,p_commentaire:null}});clearStockOpId('confirm-'+id);const anomaly=JSON.stringify(result).includes('ANOMALIE');shell(`<div class="success"><div>${anomaly?'⚠':'✓'}</div><h1>${anomaly?'Anomalie enregistrée':'Flux clôturé'}</h1><p>${anomaly?'L’écart est conservé pour résolution. Aucun historique n’est effacé.':'La source et la destination sont d’accord. Le cycle est terminé.'}</p><button class="primary" onclick="operationalInbox('confirmations')">Retour</button></div>`)}catch(e){shell(`<div class="title"><h1>Confirmation non enregistrée</h1><p>${esc(e.message)}</p></div><button class="primary" onclick="operationalFlowDetail('${id}','confirmations')">Retour</button>`,'home()')}}
