function canReceiveBoutique104(){return currentUser?.assignments.some(a=>a.site==='Boutique 104'&&['GERANT','VENDEUR','PATRON'].includes(a.role))}
const baseHome=home;
home=function(){baseHome();if(canReceiveBoutique104()){const cards=[...document.querySelectorAll('.card')];const r=cards.find(b=>b.textContent.includes('Réceptions'));if(r){r.onclick=()=>receptionsInbox();r.querySelector('small').textContent='🔴 Contrôler les arrivages en transit';}}}
async function receptionsInbox(){
 if(!canReceiveBoutique104()){shell(`<div class="title"><small>SÉCURITÉ</small><h1>Accès non autorisé</h1></div>`,'home()');return}
 shell(`<div class="title"><small>BOUTIQUE 104</small><h1>Réceptions</h1><p>Chargement…</p></div>`,'home()');
 try{const flows=await authApi('flux_stock','flux_stock_id,statut,cree_le',`&detenteur_destination_id=eq.${BOUTIQUE104_HOLDER}&statut=eq.EN_TRANSIT&order=cree_le.asc`);if(!flows.length){shell(`<div class="title"><small>BOUTIQUE 104</small><h1>Réceptions</h1><p>Aucune livraison à contrôler.</p></div><div class="empty">Tout est à jour.</div>`,'home()');return}shell(`<div class="title"><small>BOUTIQUE 104</small><h1>Réceptions 🔴 ${flows.length}</h1><p>Livraisons en attente de contrôle</p></div><section class="list">${flows.map(f=>`<article class="product-row"><div class="grow"><strong>Livraison ${esc(f.flux_stock_id.slice(0,8))}</strong><span>${esc(new Date(f.cree_le).toLocaleString('fr-FR'))} · EN TRANSIT</span></div><button onclick="receptionDetail('${f.flux_stock_id}')">→</button></article>`).join('')}</section>`,'home()')}catch(e){shell(`<div class="title"><small>ERREUR</small><h1>Réceptions indisponibles</h1><p>${esc(e.message)}</p></div>`,'home()')}
}
async function receptionDetail(id){
 shell(`<div class="title"><small>RÉCEPTION</small><h1>Chargement…</h1></div>`,'receptionsInbox()');
 try{const lines=await authApi('lignes_flux_stock','ligne_flux_stock_id,reference_produit_id,quantite_demandee',`&flux_stock_id=eq.${encodeURIComponent(id)}`);if(lines.length!==1)throw new Error('Ce test POC attend une seule ligne.');const l=lines[0];const refs=await request(`/rest/v1/references_produit?select=libelle_reference&reference_produit_id=eq.${l.reference_produit_id}`);const events=await authApi('evenements_lignes_flux_stock','quantite,decision',`&ligne_flux_stock_id=eq.${l.ligne_flux_stock_id}&type_evenement=eq.DECISION_MAGASINIER`);const shipped=events[0]?.quantite??l.quantite_demandee;shell(`<div class="title"><small>LIVRAISON ${esc(id.slice(0,8))}</small><h1>Contrôler la réception</h1><p>Dépôt Marché Central → Boutique 104</p></div><section class="list"><article class="product-row"><div class="grow"><strong>${esc(refs[0]?.libelle_reference||'Référence')}</strong><span>Quantité expédiée par Joel : <b>${shipped}</b></span></div></article></section><label>Quantité réellement reçue</label><input id="receivedQty" type="number" min="0" step="1" value="${shipped}"><label>Commentaire (optionnel)</label><input id="receivedComment" maxlength="300" placeholder="Ex. carton abîmé, quantité manquante…"><button class="primary" onclick="submitReception('${id}','${l.ligne_flux_stock_id}',${shipped})">✓ Confirmer la quantité reçue</button><button class="primary secondary" onclick="refuseReception('${id}','${l.ligne_flux_stock_id}')">Refuser la réception</button>`,'receptionsInbox()')}catch(e){shell(`<div class="title"><small>ERREUR</small><h1>Livraison inaccessible</h1><p>${esc(e.message)}</p></div>`,'receptionsInbox()')}
}
async function submitReception(id,lineId,shipped){const q=Number(document.querySelector('#receivedQty').value);if(!Number.isInteger(q)||q<0){alert('Entre une quantité entière positive ou zéro.');return}const decision=q===shipped?'VALIDE':'MODIFIE';await sendReception(id,lineId,q,decision)}
async function refuseReception(id,lineId){if(confirm('Confirmer le refus de cette réception ?'))await sendReception(id,lineId,0,'REFUSE')}
async function sendReception(id,lineId,q,decision){const comment=document.querySelector('#receivedComment')?.value?.trim()||null;try{await request('/rest/v1/rpc/recevoir_flux_stock_idempotent',{method:'POST',auth:true,body:{p_operation_client_id:stockOpId('receive-'+id),p_flux_stock_id:id,p_lignes:[{ligne_flux_stock_id:lineId,quantite_recue:q,decision}],p_commentaire:comment}});clearStockOpId('receive-'+id);shell(`<div class="success"><div>✓</div><h1>Réception déclarée</h1><p>Quantité déclarée : ${q}. La déclaration est enregistrée séparément et attend maintenant la confirmation du magasinier.</p><button class="primary" onclick="home()">Retour à l’accueil</button></div>`)}catch(e){shell(`<div class="title"><small>RÉCEPTION REFUSÉE</small><h1>Aucun changement enregistré</h1><p>${esc(e.message)}</p></div><button class="primary" onclick="receptionDetail('${id}')">Retour</button>`,'receptionsInbox()')}
}
