// Coquille UX commune. Un contexte représente soit la vue globale, soit un site
// physique, soit l'activité mobile exclusive d'un déstockeur.
const GLOBAL_CONTEXT='__global__';
const MOBILE_CONTEXT='__mobile__';
let activeContextSiteId=sessionStorage.getItem('bm_site_id')||'';

function operationalAssignments(){return currentUser?.assignments.filter(a=>a.siteId)||[]}
function globalAssignments(){return currentUser?.assignments.filter(a=>!a.siteId&&a.role!=='DESTOCKEUR')||[]}
function isDestockerUser(){return currentUser?.assignments.some(a=>a.role==='DESTOCKEUR'&&!a.siteId)}
function availableSites(){const seen=new Map();operationalAssignments().forEach(a=>{if(!seen.has(a.siteId))seen.set(a.siteId,{id:a.siteId,name:a.site,roles:[]});const site=seen.get(a.siteId);if(!site.roles.includes(a.role))site.roles.push(a.role)});return [...seen.values()]}
function availableContexts(){const contexts=[];if(globalAssignments().length)contexts.push({id:GLOBAL_CONTEXT,name:'Vue globale',kind:'GLOBAL'});if(isDestockerUser())contexts.push({id:MOBILE_CONTEXT,name:'Activité mobile',kind:'MOBILE'});availableSites().forEach(s=>contexts.push({...s,kind:'SITE'}));return contexts}
function currentContext(){const contexts=availableContexts();let context=contexts.find(c=>c.id===activeContextSiteId);if(!context)context=contexts[0]||{id:GLOBAL_CONTEXT,name:'Vue globale',kind:'GLOBAL'};if(context.id!==activeContextSiteId){activeContextSiteId=context.id;sessionStorage.setItem('bm_site_id',context.id)}return context}
function currentSiteContext(){const context=currentContext();return context.kind==='SITE'?context:null}
function setSiteContext(id){activeContextSiteId=id;sessionStorage.setItem('bm_site_id',id);cart=[];if(typeof activeRequestRoute!=='undefined')activeRequestRoute=null;home()}
function rolesHere(){const context=currentContext();if(context.kind==='SITE')return context.roles||[];if(context.kind==='MOBILE')return ['DESTOCKEUR'];return globalAssignments().map(a=>a.role)}
function hasRoleHere(role){return rolesHere().includes(role)}
function humanRole(role){return ({MAGASINIER:'Magasinier',VENDEUR:'Vendeur',GERANT:'Gérant',PATRON:'Patron',DESTOCKEUR:'Déstockeur',ADMINISTRATEUR:'Administrateur'})[role]||role}
function contextIcon(kind){return kind==='SITE'?'📍':kind==='MOBILE'?'🚶':'🌐'}
function contextPicker(){const contexts=availableContexts(),current=currentContext();if(contexts.length<=1)return `<div class="context-pill">${contextIcon(current.kind)} ${esc(current.name)}</div>`;return `<label class="context-select"><span>${contextIcon(current.kind)}</span><select aria-label="Changer d’espace" onchange="setSiteContext(this.value)">${contexts.map(c=>`<option value="${c.id}" ${c.id===current.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`}

function openGlobalSearch(){if(hasRoleHere('ADMINISTRATEUR'))adminCatalog();else catalog();setTimeout(()=>{const field=document.querySelector('#catalog-search, input[type="search"]');if(field){field.focus();field.scrollIntoView({block:'center'})}},0)}
function shell(content,back=''){const initial=esc((currentUser?.nom||'?').charAt(0).toUpperCase()),name=esc(currentUser?.nom||'Mon profil');app.innerHTML=`<header class="app-header">${back?`<button class="back" aria-label="Retour" onclick="${back}">←</button>`:brandMark(true)}<button class="global-search" aria-label="Rechercher un produit" onclick="openGlobalSearch()"><b aria-hidden="true">⌕</b><span>Rechercher un produit…</span></button><div class="header-context">${contextPicker()}</div><button class="header-task" aria-label="Voir les tâches à traiter" onclick="taskHub()">✓</button><button class="profile-trigger" aria-label="Ouvrir mon profil" onclick="profile()"><span class="avatar">${initial}</span><span class="profile-copy"><strong>${name}</strong><small>${esc(roleLabel())}</small></span></button></header>${content}`}
function actionCard(icon,title,desc,onclick,wide=false,tone=''){return `<button class="card ${wide?'wide':''} ${tone}" onclick="${onclick}"><b aria-hidden="true">${icon}</b><span>${title}</span><small>${desc}</small><i aria-hidden="true">→</i></button>`}
function roleLabel(){const roles=rolesHere();return roles.length?roles.map(humanRole).join(' · '):'Accès sécurisé'}
function metricCard(id,label,action){return `<button class="metric" onclick="${action}"><strong id="${id}">—</strong><span>${label}</span></button>`}
function globalDashboard(roles,contextId){if(roles.includes('PATRON'))return `<section class="dashboard" data-home-context="${esc(contextId)}"><div class="dashboard-title"><div><small>VUE D’ENSEMBLE</small><h2>Situation du réseau</h2></div><span class="live-dot">Dev</span></div><div class="metrics">${metricCard('metric-stock-alerts','Anomalies stock','patronAnomalies()')}${metricCard('metric-money-actions','Décisions argent','patronMoney()')}${metricCard('metric-stock-flows','Flux stock','patronStockFlows()')}</div><p class="dashboard-note" id="metric-status" aria-live="polite">Mise à jour des indicateurs…</p></section>`;if(roles.includes('ADMINISTRATEUR'))return `<section class="dashboard" data-home-context="${esc(contextId)}"><div class="dashboard-title"><div><small>ORGANISATION</small><h2>État de la configuration</h2></div><span class="live-dot">Dev</span></div><div class="metrics">${metricCard('metric-active-users','Utilisateurs actifs','adminUsers()')}${metricCard('metric-active-sites','Sites actifs','adminSites()')}${metricCard('metric-active-routes','Routes actives','adminConsole()')}</div><p class="dashboard-note" id="metric-status" aria-live="polite">Mise à jour des indicateurs…</p></section>`;return ''}
function operationalDashboard(roles,contextId){const title=roles.includes('DESTOCKEUR')?'Mon activité mobile':roles.includes('MAGASINIER')?'Travail du stock':roles.includes('GERANT')?'Activité de la boutique':'Ma journée';let metrics='';if(roles.includes('MAGASINIER'))metrics=metricCard('metric-requests','À préparer',"operationalInbox('requests')")+metricCard('metric-incoming','À recevoir',"operationalInbox('returns')")+metricCard('metric-confirmations','À confirmer',"operationalInbox('confirmations')");else if(roles.includes('DESTOCKEUR'))metrics=metricCard('metric-outgoing','Retours à envoyer',"operationalInbox('outgoing')")+metricCard('metric-incoming','Stock à recevoir',"operationalInbox('receipts')")+metricCard('metric-confirmations','Retours à confirmer',"operationalInbox('confirmations')");else if(roles.includes('GERANT'))metrics=metricCard('metric-incoming','À recevoir',"operationalInbox('receipts')")+metricCard('metric-money-tasks','Caisse à traiter','moneyTasks()')+metricCard('metric-active-flows','Flux en cours','flowHub()');else if(roles.includes('VENDEUR'))metrics=metricCard('metric-incoming','À recevoir',"operationalInbox('receipts')")+metricCard('metric-today-revenue','Recette du jour','moneyRevenue()')+metricCard('metric-active-flows','Flux en cours','flowHub()');if(!metrics)return '';return `<section class="dashboard" data-home-context="${esc(contextId)}"><div class="dashboard-title"><div><small>À FAIRE</small><h2>${title}</h2></div><span class="live-dot">Dev</span></div><div class="metrics">${metrics}</div><p class="dashboard-note" id="metric-status" aria-live="polite">Mise à jour des indicateurs…</p></section>`}
function setMetric(id,value){const node=document.getElementById(id);if(node)node.textContent=String(value)}
async function loadGlobalMetrics(roles,contextId){if(currentContext().id!==contextId)return;try{if(roles.includes('PATRON')){const [stockAlerts,moneyActions,stockFlows]=await Promise.all([authApi('flux_stock','flux_stock_id','&statut=eq.ANOMALIE'),authApi('flux_argent','flux_argent_id,statut','&statut=in.(A_VALIDER_PATRON,ANOMALIE_PATRON)'),authApi('flux_stock','flux_stock_id')]);if(currentContext().id!==contextId)return;setMetric('metric-stock-alerts',stockAlerts.length);setMetric('metric-money-actions',moneyActions.length);setMetric('metric-stock-flows',stockFlows.length)}else if(roles.includes('ADMINISTRATEUR')){const [users,sites,stockRoutes,moneyRoutes]=await Promise.all([authApi('utilisateurs','user_id','&actif=eq.true'),authApi('sites','site_id','&actif=eq.true'),authApi('routes_flux_stock','route_flux_stock_id','&actif=eq.true'),authApi('routes_financieres','route_financiere_id','&actif=eq.true')]);if(currentContext().id!==contextId)return;setMetric('metric-active-users',users.length);setMetric('metric-active-sites',sites.length);setMetric('metric-active-routes',stockRoutes.length+moneyRoutes.length)}const status=document.getElementById('metric-status');if(status)status.textContent='Indicateurs à jour'}catch(error){const status=document.getElementById('metric-status');if(status)status.textContent='Indicateurs momentanément indisponibles'}}
async function loadOperationalMetrics(roles,contextId){if(currentContext().id!==contextId)return;try{const holder=await contextHolder();if(!holder)throw new Error('Détenteur introuvable');const needsMoney=roles.some(r=>['GERANT','VENDEUR'].includes(r)),needsRevenue=roles.includes('VENDEUR');const [flows,money,revenues]=await Promise.all([authApi('flux_stock','flux_stock_id,type_flux_stock_id,detenteur_source_id,detenteur_destination_id,statut'),needsMoney?authApi('flux_argent','flux_argent_id,detenteur_source_id,detenteur_destination_id,statut'):Promise.resolve([]),needsRevenue?authApi('recettes','recette_id,site_id,date_recette',`&site_id=eq.${encodeURIComponent(currentSiteContext()?.id||'')}&date_recette=eq.${new Date().toISOString().slice(0,10)}`):Promise.resolve([])]);if(currentContext().id!==contextId)return;const id=holder.detenteur_stock_id,incoming=flows.filter(f=>f.detenteur_destination_id===id&&f.statut==='EN_TRANSIT').length,active=flows.filter(f=>(f.detenteur_source_id===id||f.detenteur_destination_id===id)&&!['CLOTURE','REFUSE'].includes(f.statut)).length,moneyTasks=money.filter(f=>(f.detenteur_source_id===id&&f.statut==='A_CONFIRMER_SOURCE')||(f.detenteur_destination_id===id&&f.statut==='ANOMALIE_CORRIGEABLE')).length;setMetric('metric-incoming',incoming);setMetric('metric-active-flows',active);setMetric('metric-money-tasks',moneyTasks);setMetric('metric-today-revenue',revenues.length);if(roles.includes('MAGASINIER'))setMetric('metric-requests',flows.filter(f=>f.detenteur_source_id===id&&['DEMANDE','EN_TRAITEMENT'].includes(f.statut)).length);if(roles.some(r=>['MAGASINIER','DESTOCKEUR'].includes(r)))setMetric('metric-confirmations',flows.filter(f=>f.detenteur_source_id===id&&f.statut==='A_CONFIRMER_MAGASINIER').length);if(roles.includes('DESTOCKEUR'))setMetric('metric-outgoing',flows.filter(f=>f.detenteur_source_id===id&&['DEMANDE','EN_TRAITEMENT'].includes(f.statut)).length);const status=document.getElementById('metric-status');if(status)status.textContent='Indicateurs à jour'}catch(error){const status=document.getElementById('metric-status');if(status)status.textContent='Indicateurs momentanément indisponibles'}}

function home(){const context=currentContext(),ctx=currentSiteContext(),roles=rolesHere(),mag=roles.includes('MAGASINIER'),seller=roles.includes('VENDEUR'),manager=roles.includes('GERANT'),patron=roles.includes('PATRON'),destocker=roles.includes('DESTOCKEUR'),admin=roles.includes('ADMINISTRATEUR');let cards='';
  if(patron){cards+=actionCard('✓','Décisions à prendre','Voir toutes les actions qui vous attendent','taskHub()',true,'attention');cards+=actionCard('📊','Stocks par détenteur','Voir chaque site physique et activité mobile','patronStocks()',true);cards+=actionCard('↔','Flux de stock','Suivre les mouvements entre détenteurs','patronStockFlows()');cards+=actionCard('⚠','Anomalies de stock','Enquêter et résoudre les écarts','patronAnomalies()');cards+=actionCard('💰','Mouvements d’argent','Retraits, remises et arbitrages','patronMoney()');cards+=actionCard('📦','Catalogue produits','Consulter les produits et références','catalog()',true)}
  if(admin){cards+=actionCard('🧴','Produits','Ajouter et organiser le catalogue','adminCatalog()',true);cards+=actionCard('👥','Équipe','Gérer les personnes et leurs responsabilités','adminTeamHub()',true);cards+=actionCard('🏬','Boutiques et circulation','Organiser les lieux, le stock et les remises d’argent','adminNetworkHub()',true);cards+=actionCard('✓','Contrôle','Consulter l’historique des modifications','adminControlHub()',true)}
  if(ctx&&mag){cards+=actionCard('📥','Nouvel arrivage fournisseur','Réceptionner une grosse livraison','startSupplierArrival()',true,'attention');cards+=actionCard('📊','Stock réseau','Répartition des SKU sur mes sites autorisés','stockNetwork()',true);cards+=actionCard('📥','Demandes à préparer','Accepter, ajuster et préparer les demandes',"operationalInbox('requests')",true);cards+=actionCard('🚚','Envoyer du stock','Créer une expédition autorisée',"startStockFlow('REAPPROVISIONNEMENT','out')");cards+=actionCard('↩','Recevoir un retour','Contrôler les produits retournés',"operationalInbox('returns')");cards+=actionCard('✓','Confirmer une réception','Valider le contrôle du destinataire',"operationalInbox('confirmations')");cards+=actionCard('📦','Consulter les produits','Catalogue et conditionnements','catalog()',true)}
  if(ctx&&manager){cards+=actionCard('💰','Recette et caisse','Recette, remises et demandes de retrait','moneyHome()',true);cards+=actionCard('＋','Demander du stock','Créer une demande de réapprovisionnement','startRequest()');cards+=actionCard('🚚','Contrôler un arrivage','Voir les réceptions en attente',"operationalInbox('receipts')");cards+=actionCard('↩','Retourner du stock','Renvoyer des produits vers un stock autorisé',"startStockFlow('RETOUR','out')");cards+=actionCard('⇄','Transférer du stock','Envoyer vers une autre boutique autorisée',"startStockFlow('TRANSFERT','out')");cards+=actionCard('📦','Consulter les produits','Catalogue et conditionnements','catalog()',true)}
  if(ctx&&seller&&!manager){cards+=actionCard('💰','Déclarer la recette','Saisir le cash et le Mobile Money','moneyRevenue()',true);cards+=actionCard('＋','Demander du stock','Créer une demande simple','startRequest()');cards+=actionCard('🚚','Contrôler un arrivage','Voir les réceptions en attente',"operationalInbox('receipts')");cards+=actionCard('📦','Trouver un produit','Rechercher une marque ou un format','catalog()',true)}
  if(destocker){cards+=actionCard('↩','Retourner des invendus','Créer puis expédier un retour vers la boutique',"startStockFlow('RETOUR','out')",true,'attention');cards+=actionCard('📤','Retours à envoyer','Préparer les retours déjà créés',"operationalInbox('outgoing')");cards+=actionCard('📥','Recevoir du stock','Contrôler les produits reçus',"operationalInbox('receipts')");cards+=actionCard('✓','Confirmer un retour','Valider le contrôle effectué par la boutique',"operationalInbox('confirmations')");cards+=actionCard('💰','Ma caisse mobile','Confirmer mes remises et consulter l’historique','destockerMoneyHome()',true);cards+=actionCard('📦','Produits à déstocker','Consulter les produits et formats','catalog()',true)}
  if(!cards)cards=actionCard('📦','Consulter les produits','Rechercher une marque, un produit ou un format','catalog()',true);
  const global=globalDashboard(roles,context.id),dashboard=global||operationalDashboard(roles,context.id),intro=patron?'Voici l’essentiel de votre réseau.':admin?'Configurez simplement l’organisation et les accès.':mag?'Préparez, recevez et suivez les stocks autorisés.':manager?'Votre boutique en un coup d’œil.':destocker?'Voici ce qu’il reste à faire aujourd’hui.':'Retrouvez vos actions du jour.';shell(`<main class="crm-home role-${patron?'patron':admin?'admin':mag?'magasinier':manager?'gerant':destocker?'destockeur':'equipe'}"><section class="welcome"><span>Bonjour ${esc(currentUser?.nom)} 👋</span><h1>${patron?'Pilotage':admin?'Administration':destocker?'Activité mobile':esc(context.name)}</h1><p>${esc(intro)}</p><small>${esc(roleLabel())}${(patron||admin)?' · '+esc(context.name):''}</small></section>${dashboard}<section class="section-heading"><div><small>ACCÈS RAPIDES</small><h2>${patron?'Piloter l’activité':admin?'Gérer l’organisation':mag?'Gérer les mouvements':manager?'Gérer la boutique':seller?'Travailler simplement':'Que voulez-vous faire ?'}</h2></div></section><section class="grid">${cards}</section></main>${nav('home')}`);if(global)void loadGlobalMetrics(roles,context.id);else if(dashboard)void loadOperationalMetrics(roles,context.id)
}

function taskHub(){const ctx=currentSiteContext(),roles=rolesHere(),patron=roles.includes('PATRON'),mag=roles.includes('MAGASINIER'),manager=roles.includes('GERANT'),seller=roles.includes('VENDEUR'),destocker=roles.includes('DESTOCKEUR');let cards='';if(patron){cards+=actionCard('⚠','Anomalies de stock','Enquêter et prendre une décision','patronAnomalies()',true,'attention');cards+=actionCard('💰','Décisions financières','Valider les retraits et arbitrer les remises','patronMoney()',true)}if(ctx&&mag){cards+=actionCard('📥','Demandes reçues','Accepter, modifier ou refuser',"operationalInbox('requests')",true,'attention');cards+=actionCard('↩','Retours à réceptionner','Contrôler les retours entrants',"operationalInbox('returns')");cards+=actionCard('✓','Réceptions à confirmer','Comparer les quantités reçues',"operationalInbox('confirmations')")}if(ctx&&(manager||seller)){cards+=actionCard('🚚','Réceptions','Contrôler les arrivages',"operationalInbox('receipts')",true);cards+=actionCard('💰','Opérations de caisse','Remises à confirmer ou corriger','moneyTasks()')}if(destocker){cards+=actionCard('📤','Retours à envoyer','Préparer et expédier les invendus',"operationalInbox('outgoing')",true,'attention');cards+=actionCard('🚚','Stock à réceptionner','Contrôler mes arrivages',"operationalInbox('receipts')");cards+=actionCard('✓','Retours à confirmer','Valider le contrôle de la boutique',"operationalInbox('confirmations')");cards+=actionCard('💰','Remises d’argent','Confirmer ou contester les montants','moneyTasks()')}if(!cards)cards='<div class="empty-state"><b>✓</b><h2>Tout est à jour</h2><p>Aucune action n’est disponible dans cet espace.</p></div>';shell(`<div class="title"><small>À TRAITER</small><h1>Mes tâches</h1><p>Retrouvez ici uniquement les actions qui demandent votre attention.</p></div><section class="grid">${cards}</section>${nav('tasks')}`)}

function flowHub(){const ctx=currentSiteContext(),roles=rolesHere(),patron=roles.includes('PATRON'),destocker=roles.includes('DESTOCKEUR'),mag=roles.includes('MAGASINIER'),manager=roles.includes('GERANT'),seller=roles.includes('VENDEUR');let cards='';if(patron){cards+=actionCard('📊','Stocks par détenteur','Situation de chaque site et activité mobile','patronStocks()',true);cards+=actionCard('↔','Flux de stock','Historique des mouvements du réseau','patronStockFlows()');cards+=actionCard('💰','Mouvements financiers','Retraits, remises et arbitrages','patronMoney()');cards+=actionCard('⚠','Anomalies de stock','Flux nécessitant une décision','patronAnomalies()')}if(ctx&&(mag||manager||seller)){if(mag){cards+=actionCard('📥','Arrivages fournisseurs','Enregistrer et retrouver les bons de livraison','supplierArrivalHome()',true);cards+=actionCard('📊','Stock réseau','Répartition des SKU sur mes sites autorisés','stockNetwork()',true);cards+=actionCard('↔','Mouvements de stock','Historique limité à mes sites','authorizedStockMovements()')}cards+=actionCard('🚚','Réceptions','Flux qui arrivent vers cet espace',"operationalInbox('receipts')",true);if(mag)cards+=actionCard('📤','Demandes et expéditions','Flux qui partent de ce stock',"operationalInbox('requests')");if(!mag)cards+=actionCard('💰','Historique financier','Recettes et mouvements d’argent','moneyHistory()')}if(destocker){cards+=actionCard('📤','Mes retours','Préparer les invendus à renvoyer',"operationalInbox('outgoing')",true);cards+=actionCard('🚚','Mes réceptions','Stock reçu dans mon activité mobile',"operationalInbox('receipts')");cards+=actionCard('✓','Contrôles à confirmer','Finaliser mes retours reçus par la boutique',"operationalInbox('confirmations')");cards+=actionCard('💰','Mes remises','Historique de ma caisse mobile','moneyHistory()')}if(!cards)cards='<div class="empty-state"><b>↔</b><h2>Aucun flux accessible</h2><p>Les flux disponibles dépendent de votre rôle.</p></div>';shell(`<div class="title"><small>SUIVI</small><h1>Flux et historique</h1><p>Consultez les mouvements liés à votre espace.</p></div><section class="grid">${cards}</section>`,'moreHub()')}

function moreHub(){const roles=rolesHere(),admin=roles.includes('ADMINISTRATEUR'),hasMoney=currentSiteContext()||roles.includes('DESTOCKEUR')||roles.includes('PATRON');let cards=actionCard('↔','Flux et historique','Suivre les mouvements autorisés','flowHub()',true);if(hasMoney)cards+=actionCard('💰','Argent','Recettes, remises et retraits',roles.includes('PATRON')?'patronMoney()':roles.includes('DESTOCKEUR')?'destockerMoneyHome()':'moneyHome()');if(admin)cards+=actionCard('⚙','Administration','Organisation et droits d’accès','adminConsole()');cards+=actionCard('◉','Mon profil','Mes rôles, mes sites et ma session','profile()',true);shell(`<div class="title"><small>PLUS</small><h1>Autres fonctions</h1><p>Les outils disponibles dans votre espace.</p></div><section class="grid">${cards}</section>${nav('more')}`)}

function nav(active=''){const item=(id,icon,label,action)=>`<button class="${active===id?'active':''}" onclick="${action}" ${active===id?'aria-current="page"':''}><b aria-hidden="true">${icon}</b><span>${label}</span></button>`,roles=rolesHere(),admin=roles.includes('ADMINISTRATEUR'),patron=roles.includes('PATRON'),mag=roles.includes('MAGASINIER')&&Boolean(currentSiteContext()),manager=roles.includes('GERANT'),destocker=roles.includes('DESTOCKEUR');if(admin)return `<nav class="admin-nav" aria-label="Navigation principale de l’administration">${item('home','⌂','Accueil','home()')}${item('products','⌕','Produits','adminCatalog()')}${item('team','♙','Équipe','adminTeamHub()')}${item('network','↔','Boutiques','adminNetworkHub()')}${item('control','✓','Contrôle','adminControlHub()')}</nav>`;if(patron)return `<nav aria-label="Navigation principale du patron">${item('home','⌂','Accueil','home()')}${item('tasks','✓','À traiter','taskHub()')}${item('stock','▦','Stocks','patronStocks()')}${item('flows','↔','Flux','flowHub()')}${item('more','•••','Plus','moreHub()')}</nav>`;if(mag)return `<nav aria-label="Navigation principale du magasinier">${item('home','⌂','Accueil','home()')}${item('tasks','✓','À traiter','taskHub()')}${item('stock','▦','Stock','stockNetwork()')}${item('flows','↔','Flux','flowHub()')}${item('more','•••','Plus','moreHub()')}</nav>`;if(manager)return `<nav aria-label="Navigation principale du gérant">${item('home','⌂','Accueil','home()')}${item('tasks','✓','À traiter','taskHub()')}${item('products','⌕','Produits','catalog()')}${item('money','₣','Caisse','moneyHome()')}${item('more','•••','Plus','moreHub()')}</nav>`;if(destocker)return `<nav aria-label="Navigation principale du déstockeur">${item('home','⌂','Accueil','home()')}${item('tasks','✓','À traiter','taskHub()')}${item('products','⌕','Produits','catalog()')}${item('money','₣','Caisse','destockerMoneyHome()')}${item('more','•••','Plus','moreHub()')}</nav>`;return `<nav aria-label="Navigation principale">${item('home','⌂','Accueil','home()')}${item('tasks','✓','À traiter','taskHub()')}${item('products','⌕','Produits','catalog()')}${item('more','•••','Plus','moreHub()')}</nav>`}
