let activeContextSiteId=sessionStorage.getItem('bm_site_id')||'';
function operationalAssignments(){return currentUser?.assignments.filter(a=>a.siteId)||[]}
function availableSites(){const seen=new Map();operationalAssignments().forEach(a=>{if(!seen.has(a.siteId))seen.set(a.siteId,{id:a.siteId,name:a.site,roles:[]});seen.get(a.siteId).roles.push(a.role)});return [...seen.values()]}
function currentSiteContext(){const sites=availableSites();let site=sites.find(s=>s.id===activeContextSiteId);if(!site)site=sites[0]||null;if(site&&site.id!==activeContextSiteId){activeContextSiteId=site.id;sessionStorage.setItem('bm_site_id',site.id)}return site}
function setSiteContext(id){activeContextSiteId=id;sessionStorage.setItem('bm_site_id',id);home()}
function rolesHere(){return currentSiteContext()?.roles||currentUser?.assignments.filter(a=>!a.siteId).map(a=>a.role)||[]}
function hasRoleHere(role){return rolesHere().includes(role)}
function humanRole(role){return ({MAGASINIER:'Magasinier',VENDEUR:'Vendeur',GERANT:'Gérant',PATRON:'Patron',ADMINISTRATEUR:'Administrateur'})[role]||role}
function contextPicker(){const sites=availableSites();if(!sites.length)return '<div class="context-pill">🌐 Accès global</div>';if(sites.length===1)return `<div class="context-pill">📍 ${esc(sites[0].name)}</div>`;return `<label class="context-select">📍 <select onchange="setSiteContext(this.value)">${sites.map(s=>`<option value="${s.id}" ${s.id===currentSiteContext()?.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>`}
function shell(content,back=''){const initial=esc((currentUser?.nom||'?').charAt(0).toUpperCase());app.innerHTML=`<header>${back?`<button class="back" onclick="${back}">←</button><div class="header-context">${contextPicker()}</div>`:`<div><small>BOUTIQUE MANAGER</small><h1>Bonjour ${esc(currentUser?.nom)} 👋</h1>${contextPicker()}</div><button class="avatar" onclick="profile()">${initial}</button>`}</header>${content}`}
function actionCard(icon,title,desc,onclick,wide=false){return `<button class="card ${wide?'wide':''}" ${onclick?`onclick="${onclick}"`:'disabled'}><b>${icon}</b><span>${title}</span><small>${desc}</small></button>`}
function home(){const ctx=currentSiteContext(),roles=rolesHere(),globalAdmin=currentUser?.assignments.some(a=>a.role==='ADMINISTRATEUR'&&!a.siteId),mag=roles.includes('MAGASINIER'),seller=roles.includes('VENDEUR'),manager=roles.includes('GERANT'),patron=roles.includes('PATRON');let cards='';if(mag){cards+=actionCard('📥','Demandes à traiter','Voir les demandes adressées à ce stock','requestsInbox()',true);cards+=actionCard('📦','Préparations','Préparer et expédier les demandes','requestsInbox()');cards+=actionCard('✓','Inventaire','Compter et corriger le stock','');}if(seller||manager||patron){cards+=actionCard('＋','Demander du stock','Créer rapidement une demande','startRequest()',true);cards+=actionCard('🚚','Réceptions','Contrôler les arrivages','');cards+=actionCard('📦','Stock disponible','Voir ce qui est disponible','catalog()');}cards+=actionCard('⌕','Rechercher un produit','Marque, produit, variante, format','catalog()',true);cards+=actionCard('↔','Flux de stock','Suivre demandes et mouvements','');if(manager){cards+=actionCard('💰','Recettes','Saisir et suivre les recettes','');cards+=actionCard('↗','Remises','Enregistrer les remises','');}if(patron){cards+=actionCard('⚠','Alertes & anomalies','Voir les points à contrôler','patronAnomalies()');}if(globalAdmin){cards+=`</section><h2 class="section-muted">Administration</h2><section class="grid admin-grid">${actionCard('⚙️','Routes de stock','Configurer les trajets autorisés','adminStockRoutes()')}`;}const roleLabel=roles.length?roles.map(humanRole).join(' · '):(globalAdmin?'Administrateur':'Accès');shell(`<section class="home-summary"><span>${ctx?'Mon espace':'Mon accès'}</span><strong>${esc(ctx?.name||'Global')}</strong><small>${esc(roleLabel)}</small></section><h2>Que voulez-vous faire ?</h2><section class="grid">${cards}</section>${nav()}`)}
function nav(){return `<nav><button class="active" onclick="home()">⌂<span>Accueil</span></button><button onclick="catalog()">⌕<span>Produits</span></button><button>↔<span>Flux</span></button><button onclick="profile()">◉<span>Profil</span></button></nav>`}
