let activeContextSiteId=sessionStorage.getItem('bm_site_id')||'';
function operationalAssignments(){return currentUser?.assignments.filter(a=>a.siteId)||[]}
function availableSites(){const seen=new Map();operationalAssignments().forEach(a=>{if(!seen.has(a.siteId))seen.set(a.siteId,{id:a.siteId,name:a.site,roles:[]});seen.get(a.siteId).roles.push(a.role)});return [...seen.values()]}
function currentSiteContext(){const sites=availableSites();let site=sites.find(s=>s.id===activeContextSiteId);if(!site)site=sites[0]||null;if(site&&site.id!==activeContextSiteId){activeContextSiteId=site.id;sessionStorage.setItem('bm_site_id',site.id)}return site}
function setSiteContext(id){activeContextSiteId=id;sessionStorage.setItem('bm_site_id',id);cart=[];activeRequestRoute=null;home()}
function rolesHere(){return currentSiteContext()?.roles||currentUser?.assignments.filter(a=>!a.siteId).map(a=>a.role)||[]}
function hasRoleHere(role){return rolesHere().includes(role)}
function humanRole(role){return ({MAGASINIER:'Magasinier',VENDEUR:'Vendeur',GERANT:'Gérant',PATRON:'Patron',DESTOCKEUR:'Déstockeur',ADMINISTRATEUR:'Administrateur'})[role]||role}
function contextPicker(){const sites=availableSites();if(!sites.length)return '<div class="context-pill">🌐 Accès global</div>';if(sites.length===1)return `<div class="context-pill">📍 ${esc(sites[0].name)}</div>`;return `<label class="context-select">📍 <select onchange="setSiteContext(this.value)">${sites.map(s=>`<option value="${s.id}" ${s.id===currentSiteContext()?.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>`}
function shell(content,back=''){const initial=esc((currentUser?.nom||'?').charAt(0).toUpperCase());app.innerHTML=`<header>${back?`<button class="back" onclick="${back}">←</button><div class="header-context">${contextPicker()}</div>`:`<div><small>BOUTIQUE MANAGER</small><h1>Bonjour ${esc(currentUser?.nom)} 👋</h1>${contextPicker()}</div><button class="avatar" onclick="profile()">${initial}</button>`}</header>${content}`}
function actionCard(icon,title,desc,onclick,wide=false){return `<button class="card ${wide?'wide':''}" ${onclick?`onclick="${onclick}"`:'disabled'}><b>${icon}</b><span>${title}</span><small>${desc}</small></button>`}
function home(){const ctx=currentSiteContext(),roles=rolesHere(),globalAdmin=currentUser?.assignments.some(a=>a.role==='ADMINISTRATEUR'&&!a.siteId),mag=roles.includes('MAGASINIER'),seller=roles.includes('VENDEUR'),manager=roles.includes('GERANT'),patron=roles.includes('PATRON'),destocker=roles.includes('DESTOCKEUR');let cards='';if(ctx&&mag){cards+=actionCard('📥','Demandes reçues','Réapprovisionnements et transferts à traiter',"operationalInbox('requests')",true);cards+=actionCard('🚚','Envoyer du stock','Réapprovisionner une boutique autorisée',"startStockFlow('REAPPROVISIONNEMENT','out')");cards+=actionCard('↩','Retours à réceptionner','Retours entrants vers ce stock',"operationalInbox('returns')");cards+=actionCard('✓','Réceptions à confirmer','Vérifier ce que le destinataire a reçu',"operationalInbox('confirmations')");cards+=actionCard('☑','Inventaire','Compter et corriger le stock','');}if(ctx&&destocker){cards+=actionCard('🏷','Déstockage','Consulter les produits à déstocker','catalog()',true);}if(ctx&&(seller||manager)){cards+=actionCard('💰','Recettes & argent','Recette, remises et retraits','moneyHome()',true);cards+=actionCard('＋','Demander du stock','Demander un réapprovisionnement','startRequest()',true);cards+=actionCard('↩','Retourner du stock','Renvoyer du stock vers un stock central',"startStockFlow('RETOUR','out')");cards+=actionCard('⇄','Transférer du stock','Envoyer vers une autre boutique autorisée',"startStockFlow('TRANSFERT','out')");cards+=actionCard('🚚','Réceptions','Contrôler les flux qui arrivent',"operationalInbox('receipts')");}if(patron&&!seller&&!manager&&!mag){cards+=actionCard('⚠','Alertes & anomalies','Points nécessitant votre attention','patronAnomalies()',true);cards+=actionCard('📦','Stocks par site','Consulter les stocks','catalog()');cards+=actionCard('↔','Flux de stock','Suivre les mouvements','');cards+=actionCard('💰','Recettes & remises','Suivre les mouvements d’argent','patronMoney()');}if(ctx){cards+=actionCard('⌕','Rechercher un produit','Marque, produit, variante, format','catalog()',true)}if(globalAdmin){cards+=actionCard('⚙️','Administration','Utilisateurs, rôles, sites, routes et journal','adminConsole()',true)}const roleLabel=roles.length?roles.map(humanRole).join(' · '):(globalAdmin?'Administrateur':'Accès');shell(`<section class="home-summary"><span>${ctx?'Mon espace':'Mon accès'}</span><strong>${esc(ctx?.name||'Global')}</strong><small>${esc(roleLabel)}</small></section><h2>Que voulez-vous faire ?</h2><section class="grid">${cards}</section>${nav()}`)}
function nav(){return `<nav><button class="active" onclick="home()">⌂<span>Accueil</span></button><button onclick="catalog()">⌕<span>Produits</span></button><button>↔<span>Flux</span></button><button onclick="profile()">◉<span>Profil</span></button></nav>`}
