const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const css = read('sam-theme.css');
const money = read('money-ux.js');
const shell = read('ux-shell.js');
const admin = read('admin-console.js');
const anomalies = read('patron-anomalies.js');
const catalogAdmin = read('catalog-admin.js');
const index = read('index.html');

assert.match(css, /button:focus-visible/);
assert.match(css, /button \{ min-height: 44px; \}/);
assert.match(css, /prefers-reduced-motion: reduce/);
assert.match(css, /@media \(min-width: 700px\)/);
assert.match(css, /@media \(min-width: 1100px\)/);
assert.match(css, /@media \(min-width: 1500px\)/);
assert.match(css, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
assert.match(css, /nav \{ left: 28px; top: 28px; bottom: 28px;/);
assert.match(shell, /aria-live="polite"/);
assert.match(money, /function readMoneyFields\(\)/);
assert.match(money, /Indiquez un montant en cash ou Mobile Money/);
assert.match(money, /label for="m-reason"/);
assert.match(money, /label for="m-source"/);
assert.match(admin, /code==='DESTOCKEUR'/);
assert.match(admin, /class="row-action"/);
assert.match(admin, /class="role-assignment"/);
assert.match(read('admin-routes.js'), /status-badge/);
assert.match(css, /\.product-row > \.row-action/);
assert.doesNotMatch(anomalies, /Expédié par Joel|reçu par Georges|Observation Joel/);
assert.match(index, /money-ux\.js\?v=8/);
assert.match(index, /sam-theme\.css\?v=11/);
assert.match(index, /catalog-admin\.js\?v=5/);
assert.match(index, /admin-routes\.js\?v=9/);
assert.match(index, /app\.js\?v=15/);
assert.match(index, /admin-console\.js\?v=11/);
assert.match(index, /admin-extras\.js\?v=3/);
assert.match(index, /ux-shell\.js\?v=16/);
assert.match(catalogAdmin, /admin_creer_produit_avec_approvisionnement/);
assert.match(catalogAdmin, /admin_generer_sku_produit/);
assert.match(catalogAdmin, /for="cp-brand"/);
assert.match(admin, /admin_creer_utilisateur_complet/);
assert.match(admin, /autocomplete="given-name"/);
assert.match(admin, /autocomplete="family-name"/);
assert.match(admin, /type="tel"/);
assert.match(read('admin-extras.js'), /admin-user-access/);
assert.match(read('admin-extras.js'), /adminPreviewSiteToggle/);
assert.match(read('app.js'), /function passwordSetupScreen/);
assert.match(read('app.js'), /photo_url/);
assert.match(read('admin-extras.js'), /adminUploadReferencePhoto/);
assert.match(css, /\.reference-photo-admin/);
assert.match(css, /\.supplier-fieldset/);
assert.match(read('admin-extras.js'), /adminLanaImports/);
assert.match(catalogAdmin, /Fabricant/);

console.log('Audit UI/accessibilité: OK');
